[tool.poetry]
name = "ep"
version = "0.1.0"
description = ""
authors = ["osangu <osangu012@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beanie = "^1.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
